# Generated by Django 2.2.5 on 2019-09-20 07:08

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20190920_0657'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='video',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
