# Generated by Django 2.2.5 on 2019-09-20 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='coverimage',
            field=models.ImageField(default='', upload_to='images/%Y/%m/%d'),
        ),
    ]
