# Generated by Django 2.2.5 on 2019-09-20 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_post_coverimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='coverimage',
            field=models.ImageField(default='', upload_to='uploads/%Y/%m/%d'),
        ),
    ]
